diff:
	git diff --no-index -U1000 v0.py v1.py  | tail +6  | grep '^[ +]' > d1.py
	git diff --no-index -U1000 v3.py v4.py  | tail +6  | grep '^[ +]' > d4.py
	git diff --no-index -U1000 v4.py v5.py  | tail +6  | grep '^[ +]' > d5.py
	git diff --no-index -U1000 v5.py v6.py  | tail +6  | grep '^[ +]' > d6.py
	git diff --no-index -U1000 v6.py v7.py  | tail +6  | grep '^[ +]' > d7.py
	git diff --no-index -U1000 v7.py v8.py  | tail +6  | grep '^[ +]' > d8.py
	git diff --no-index -U1000 v8.py v9.py  | tail +6  | grep '^[ +]' > d9.py
	git diff --no-index -U1000 v9.py v10.py  | tail +6  | grep '^[ +]' > d10.py
	git diff --no-index -U1000 v10.py v11.py  | tail +6  | grep '^[ +]' > d11.py
	git diff --no-index -U1000 v11.py v12.py  | tail +6  | grep '^[ +]' > d12.py
	git diff --no-index -U1000 v12.py v13.py  | tail +6  | grep '^[ +]' > d13.py
	git diff --no-index -U1000 v12.py v15.py  | tail +6  | grep '^[ +]' > d15.py
