variables:
  GIT_CHECKOUT: none
deploy:
  stage: deploy
  only:
    - master
  script:
    - cd /srv/nginx/curiouscoding.nl/ && git pull https://project_78_bot:$ACCESS_TOKEN@gitlab.ragnargrootkoerkamp.nl/ragnar/research.git && git submodule update
    - cd /srv/nginx/curiouscoding.nl/ && make build
  environment:
