#+title: About
#+AUTHOR: Ragnar Groot Koerkamp
#+HUGO_BASE_DIR: .
#+HUGO_SECTION: /

Hi there ;) I'm doing a PhD in bioinformatics at the [[https://bmi.inf.ethz.ch/][BMI lab]] at ETH Zurich.
Currently I'm working on near-linear algorithms for exact pairwise alignment.

This blog is where I dump my thoughts on my PhD research. For now it includes
some short notes/remarks/ideas for research, and a few longer posts that may
eventually turn into papers.

Feel free to use this blog as inspiration and build on the ideas you see here, as
long as you cite appropriately.

If you spot mistakes or have suggestions for improvement,
comment at the bottom of each page or make an issue on the [[https://github.com/RagnarGrootKoerkamp/research][GitHub]] source for
this blog.

** Trivia (i.e. i18n)

My first name is /Ragnar/.  My last name is /Groot Koerkamp/. Yes, that has a
space. No, you cannot get away with /Groot/, and no, you cannot say /Koerkamp/.

Don't even try to say /Ragnar G. Koerkamp/. In fact, my middle name starts with
a /G/, so you'd have to write /R. G. Groot Koerkamp/, or /Groot Koerkamp, R.
G./. To not complicate things more than they already are, use one of the
following for purposes of publishing and citing:

- Ragnar Groot Koerkamp,
- Groot Koerkamp, R.,
- ~Ragnar {Groot Koerkamp}~ in BibTeX files.

Note that not all BibTex exports get this right. In particular, Arxiv does not
support my name, and downloading BibTex entries (derived) from it may give wrong results.


---

Also check out my blog on all the things non-research: [[https://curiouscoding.nl][curiouscoding.nl]].
