baseurl = "https://research.curiouscoding.nl"
title = "Ragnar Groot Koerkamp | BMI @ ETH Zurich"
theme = "hugo-coder"
languagecode = "en-gb"
defaultcontentlanguage = "en-gb"

paginate = 20

pygmentsstyle = "w"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

#disqusShortname = "yourdiscussshortname"

[params]
  author = "Ragnar Groot Koerkamp"
  info = "PhD Computational Biology @ BMI ETH Zurich"
  description = "Research notes and ideas"
  keywords = "blog,developer,phd,computational biology,dna,sequencing,personal,bmi,eth,ethz,eth zurich"
  #avatarurl = "images/avatar.jpg"
  #gravatar = "john.doe@example.com"

  #favicon_32 = "/img/favicon-32x32.png"
  #favicon_16 = "/img/favicon-16x16.png"

  footercontent = "Footer text."
  hideFooter = false
  hideCredits = false
  hideCopyright = false
  since = 2021

  enableTwemoji = false

  colorScheme = "auto"
  hidecolorschemetoggle = false

  #customCSS = ["css/custom.css"]
  #customSCSS = ["scss/custom.scss"]
  #customJS = ["js/custom.js"]

[params.googleTagManager]
    id = "G-4KBZ7DMRN4"

# Needed for ox-hugo
[markup.goldmark.renderer]
  unsafe = true

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/RagnarGrootKoerkamp/"
#[[params.social]]
  #name = "Gitlab"
  #icon = "fa fa-gitlab fa-2x"
  #weight = 2
  #url = "https://gitlab.com/johndoe/"
[[params.social]]
  name = "Twitter"
  icon = "fa fa-twitter fa-2x"
  weight = 3
  url = "https://twitter.com/curious_coding/"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "Notes"
  weight = 2
  url = "notes/"
[[menu.main]]
  name = "About"
  weight = 3
  url = "about/"
