baseurl = "https://research.curiouscoding.nl"
title = "Ragnar Groot Koerkamp | BMI @ ETH Zurich"
theme = "hugo-coder"
languagecode = "en-gb"
defaultcontentlanguage = "en-gb"

paginate = 20

pygmentsstyle = "wb"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

#disqusShortname = "yourdiscussshortname"

[params]
  author = "Ragnar Groot Koerkamp"
  info = "PhD Computational Biology @ BMI ETH Zurich"
  description = "Research notes and ideas"
  keywords = "blog,developer,phd,computational biology,dna,sequencing,personal,bmi,eth,ethz,eth zurich"
  avatarurl = "/images/bike.jpg"

  favicon_32 = "/images/bike-32.png"
  favicon_16 = "/images/bike-64.png"

  footercontent = 'This blog is <a href="https://github.com/RagnarGrootKoerkamp/research">open source</a>. - Feel free to get in touch!'
  hideFooter = false
  hideCredits = false
  hideCopyright = false
  since = 2021

  enableTwemoji = false

  colorScheme = "auto"
  hidecolorschemetoggle = false

  #customCSS = ["css/custom.css"]
  #customSCSS = ["scss/custom.scss"]
  #customJS = ["js/custom.js"]

[params.googleTagManager]
    id = "G-4KBZ7DMRN4"

# Needed for ox-hugo
[markup.goldmark.renderer]
  unsafe = true

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/RagnarGrootKoerkamp/"
[[params.social]]
  name = "Twitter"
  icon = "fa fa-twitter fa-2x"
  weight = 2
  url = "https://twitter.com/curious_coding/"
[[params.social]]
  name = "LinkedIn"
  icon = "fa fa-linkedin fa-2x"
  weight = 3
  url = "https://www.linkedin.com/in/ragnargrootkoerkamp/"
[[params.social]]
  name = "Mail"
  icon = "fa fa-envelope fa-2x"
  weight = 4
  url = "mailto:ragnar.grootkoerkamp@gmail.com"
[[params.social]]
  name = "Rss"
  icon = "fa fa-rss fa-2x"
  weight = 5
  url = "index.xml"

# Menu links
[[menu.main]]
  name = "Posts"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "Notes"
  weight = 2
  url = "notes/"
[[menu.main]]
  name = "About"
  weight = 3
  url = "about/"
