#+AUTHOR: Ragnar Groot Koerkamp
#+HUGO_BASE_DIR: .
#+HUGO_SECTION: /

* About
:PROPERTIES:
:EXPORT_FILE_NAME: about
:END:

Hi there ;) I'm doing a PhD in bioinformatics at the [[https://bmi.inf.ethz.ch/][BMI lab]] at ETH Zurich.
Currently I'm working on near-linear algorithms for exact pairwise alignment.

This blog is where I dump my thoughts on my PhD research. For now it includes
some short notes/remarks/ideas for research, and a few longer posts that may
eventually turn into papers.

Feel free to use this blog as inspiration and build on the ideas you see here, as
long as you cite appropriately.

If you spot mistakes or have suggestions for improvement,
comment at the bottom of each page or make an issue on the [[https://github.com/RagnarGrootKoerkamp/research][GitHub]] source for
this blog.

---

Also check out my blog on all the things non-research: [[https://curiouscoding.nl][curiouscoding.nl]].

* Posts
:PROPERTIES:
:EXPORT_FILE_NAME: _index
:EXPORT_HUGO_SECTION: posts
:END:
Longer posts on various topics.


* Notes
:PROPERTIES:
:EXPORT_FILE_NAME: _index
:EXPORT_HUGO_SECTION: notes
:END:
These are short unprocessed thoughts and remarks. Some may eventually turn into
a post.
