#+AUTHOR: Ragnar Groot Koerkamp
#+HUGO_BASE_DIR: .
#+HUGO_SECTION: /

* About
:PROPERTIES:
:EXPORT_FILE_NAME: about
:END:
This blog will host everything related to my PhD: summaries of papers, research ideas,
quick notes and thoughts on various topics, drafts for my own papers, and who knows what else.

You can find both published (eventually, I hope) and unpublished results. Feel
free to use this blog as inspiration and build on the ideas you see here, as
long as you cite appropriately.

If you come across mistakes or have suggestions for improvement,
comment on the [[https://github.com/RagnarGrootKoerkamp/research][GitHub]] source for this blog. I am new to the field of
bioinformatics, and may not be aware of all the latest developments.

---

Also check out my blog on all the things non-research: [[https://curiouscoding.nl][curiouscoding.nl]].

* Posts
:PROPERTIES:
:EXPORT_FILE_NAME: _index
:EXPORT_HUGO_SECTION: posts
:END:
Posts on various topics.

* Notes
:PROPERTIES:
:EXPORT_FILE_NAME: _index
:EXPORT_HUGO_SECTION: notes
:END:
These are short unprocessed thoughts and remarks. Some may eventually turn into
a post.

* Papers
:PROPERTIES:
:EXPORT_FILE_NAME: _index
:EXPORT_HUGO_SECTION: papers
:END:
Work in progress papers are here.
