#+author: Ragnar Groot Koerkamp
#+hugo_base_dir: .
#+hugo_section: notes
#+hugo_auto_set_lastmod: t

* Notes
:PROPERTIES:
:EXPORT_FILE_NAME: _index
:END:
These are short unprocessed thoughts and remarks. Some may eventually turn into
a post.

* DONE Hello, World!
CLOSED: [2021-10-13]
:PROPERTIES:
:EXPORT_FILE_NAME: hello-world
:END:
#+BEGIN_SRC python
print("Hello, World!")
#+END_SRC
#+BEGIN_SRC cpp
std::cout << "Hello, World!" << std::endl;
#+END_SRC

* DONE Hugo and ox-hugo
CLOSED: [2021-10-14]
:PROPERTIES:
:EXPORT_FILE_NAME: hugo
:END:
Here's the customary /how I made this site using X/ post.

This site is built using [[https://gohugo.io][Hugo]] and [[https://ox-hugo.scripter.co/][~ox-hugo~]].

The source is written in [[https://orgmode.org/][Org mode]], which is converted to markdown by ~ox-hugo~.
To get started yourself, check out the [[https://github.com/RagnarGrootKoerkamp/research/tree/c46e8c7840d70b86746ebe1d76384893638d8bbc][initial commit]] of the source repository
and build from there.


Some notes:
- I'm using the ~Hugo-coder~ theme.
- Since the conversion from Org to markdown is done using an Emacs plugin, the
  ~emacs~ folder contains a simple ~init.el~ to import ~ox-hugo~ and a function
  to export all ~*.org~ files in the repository apart from those inside the
  ~emacs~ folder itself.
- The ~makefile~ contains the ~build-content~ rule to call the conversion, and
  ~build-site~ to invoke Hugo. Just running ~make~ will do both of these and
  serve the site locally.

* DONE Writing opinions is scary
CLOSED: [2021-10-19 Tue 17:36]
:PROPERTIES:
:EXPORT_FILE_NAME: writing
:END:
As it turns out, writing opinions is much more difficult than writing just facts.

I suppose I'll just have to write down whatever my thoughts are and go with it,
and not think about it too much.

Probably my first posts will be chaotic and have different thoughts all over the
place, but let's hope it gets better over time.

* TODO list
:PROPERTIES:
:EXPORT_FILE_NAME: todo
:END:

- Write about hypothesis on about/ page
- Set up hypothesis notifications
