all: figures

figures:
	drawio --export --format svg --transparent figs.drawio.svg --embed -p  0 -o figs/kmer.svg
	drawio --export --format svg --transparent figs.drawio.svg --embed -p  1 -o figs/window.svg
	drawio --export --format svg --transparent figs.drawio.svg --embed -p  2 -o figs/density.svg
	drawio --export --format svg --transparent figs.drawio.svg --embed -p  3 -o figs/closed.svg
	drawio --export --format svg --transparent figs.drawio.svg --embed -p  4 -o figs/closed-dist.svg
	drawio --export --format svg --transparent figs.drawio.svg --embed -p  5 -o figs/open.svg
	drawio --export --format svg --transparent figs.drawio.svg --embed -p  6 -o figs/open-dist.svg
	drawio --export --format svg --transparent figs.drawio.svg --embed -p  7 -o figs/threshold.svg
	drawio --export --format svg --transparent figs.drawio.svg --embed -p  8 -o figs/threshold-dist.svg
	drawio --export --format svg --transparent figs.drawio.svg --embed -p  9 -o figs/bd.svg
	drawio --export --format svg --transparent figs.drawio.svg --embed -p 10 -o figs/sus.svg
	drawio --export --format svg --transparent figs.drawio.svg --embed -p 11 -o figs/sus-dist.svg
	drawio --export --format svg --transparent figs.drawio.svg --embed -p 12 -o figs/anti-lex-sus.svg
	drawio --export --format svg --transparent figs.drawio.svg --embed -p 13 -o figs/anti-lex-sus-dist.svg
