all: figures

figures:
	drawio --export --format svg --transparent algorithms.drawio.svg --embed -p 0 -o naive.svg
	drawio --export --format svg --transparent algorithms.drawio.svg --embed -p 1 -o queue.svg
	drawio --export --format svg --transparent algorithms.drawio.svg --embed -p 2 -o jump.svg
	drawio --export --format svg --transparent algorithms.drawio.svg --embed -p 3 -o rescan.svg
	drawio --export --format svg --transparent algorithms.drawio.svg --embed -p 4 -o split.svg
