export file="figs.ipe":
    rm -f *.svg
    grep view {{file}} | grep -o 'name=".*"' | cut -d '"' -f 2 | xargs -I NAME -n 1 iperender -svg -page 1 -view "NAME" {{file}} NAME.svg || true
    grep view {{file}} | grep -o 'name=".*"' | cut -d '"' -f 2 | xargs -I NAME -n 1 iperender -svg -page 2 -view "NAME" {{file}} NAME.svg || true
    grep view {{file}} | grep -o 'name=".*"' | cut -d '"' -f 2 | xargs -I NAME -n 1 iperender -svg -page 3 -view "NAME" {{file}} NAME.svg || true
