ln:
  rm -rf imgs plots
  ln -sfn ../../../git/pairwise-alignment/pa-bench/evals/astarpa2/plots plots
  ln -sfn ../../../git/astarpa/imgs/astarpa2-paper imgs
  ln -sfn sparse/0.png imgs/ranges/sparse.png
  ln -sfn full/0.png imgs/ranges/full.png
  ln -sfn doubling/0.png imgs/doubling-0.png
  ln -sfn doubling/1.png imgs/doubling-1.png
