ln:
  cd results && ln -sfn ../../../../git/pairwise-alignment/pa-bench/evals/astarpa2/plots/* .
  cd intro && ln -sfn ../../../../git/astarpa/imgs/astarpa2-paper/intro/* .
  cd prepruning && ln -sfn ../../../../git/astarpa/imgs/astarpa2-paper/prepruning/* .
  cd trace && ln -sfn ../../../../git/astarpa/imgs/astarpa2-paper/trace/* .
  cd doubling && ln -sfn ../../../../git/astarpa/imgs/astarpa2-paper/doubling/* .
  cd simd && ln -sfn ../../../../git/astarpa/imgs/astarpa2-paper/simd/* .
