export file="figs/figs.ipe":
    rm -f figs/*.svg
    grep view {{file}} | grep -o 'name=".*"' | cut -d '"' -f 2 | xargs -I NAME -n 1 iperender -svg -page 1 -view "NAME" {{file}} figs/NAME.svg || true
    grep view {{file}} | grep -o 'name=".*"' | cut -d '"' -f 2 | xargs -I NAME -n 1 iperender -svg -page 2 -view "NAME" {{file}} figs/NAME.svg || true
