export file="figs.ipe":
    rm -f *.svg
    grep view {{file}} | grep -o 'name=".*"' | cut -d '"' -f 2 | xargs -I NAME -n 1 iperender -svg -page 1 -view "NAME" {{file}} fig/NAME.svg || true
    grep view {{file}} | grep -o 'name=".*"' | cut -d '"' -f 2 | xargs -I NAME -n 1 iperender -svg -page 2 -view "NAME" {{file}} fig/NAME.svg || true
    grep view {{file}} | grep -o 'name=".*"' | cut -d '"' -f 2 | xargs -I NAME -n 1 iperender -svg -page 3 -view "NAME" {{file}} fig/NAME.svg || true
    grep view {{file}} | grep -o 'name=".*"' | cut -d '"' -f 2 | xargs -I NAME -n 1 iperender -svg -page 4 -view "NAME" {{file}} fig/NAME.svg || true
    grep view {{file}} | grep -o 'name=".*"' | cut -d '"' -f 2 | xargs -I NAME -n 1 iperender -svg -page 5 -view "NAME" {{file}} fig/NAME.svg || true
    grep view {{file}} | grep -o 'name=".*"' | cut -d '"' -f 2 | xargs -I NAME -n 1 iperender -svg -page 6 -view "NAME" {{file}} fig/NAME.svg || true

png file="figs.ipe":
    rm -f png/*.png
    grep view {{file}} | grep -o 'name=".*"' | cut -d '"' -f 2 | xargs -I NAME -n 1 iperender -png -page 1 -view "NAME" -resolution 300 {{file}} png/NAME.png || true
    grep view {{file}} | grep -o 'name=".*"' | cut -d '"' -f 2 | xargs -I NAME -n 1 iperender -png -page 2 -view "NAME" -resolution 300 {{file}} png/NAME.png || true
    grep view {{file}} | grep -o 'name=".*"' | cut -d '"' -f 2 | xargs -I NAME -n 1 iperender -png -page 3 -view "NAME" -resolution 300 {{file}} png/NAME.png || true
    grep view {{file}} | grep -o 'name=".*"' | cut -d '"' -f 2 | xargs -I NAME -n 1 iperender -png -page 4 -view "NAME" -resolution 300 {{file}} png/NAME.png || true
    grep view {{file}} | grep -o 'name=".*"' | cut -d '"' -f 2 | xargs -I NAME -n 1 iperender -png -page 5 -view "NAME" -resolution 300 {{file}} png/NAME.png || true
    grep view {{file}} | grep -o 'name=".*"' | cut -d '"' -f 2 | xargs -I NAME -n 1 iperender -png -page 6 -view "NAME" -resolution 300 {{file}} png/NAME.png || true
