all: figures

figures:
	drawio --export --format svg --transparent stree.drawio --embed -p 1 -o full.svg
	drawio --export --format svg --transparent stree.drawio --embed -p 2 -o partial.svg
	drawio --export --format svg --transparent stree.drawio --embed -p 3 -o flipped.svg
	drawio --export --format svg --transparent stree.drawio --embed -p 4 -o layouts.svg
	drawio --export --format svg --transparent stree.drawio --embed -p 5 -o prefix.svg
	drawio --export --format svg --transparent stree.drawio --embed -p 6 -o prefix-compact.svg
	drawio --export --format svg --transparent stree.drawio --embed -p 7 -o prefix-l1.svg
	drawio --export --format svg --transparent stree.drawio --embed -p 8 -o prefix-overlapping.svg
	drawio --export --format svg --transparent stree.drawio --embed -p 9 -o prefix-map.svg
	drawio --export --format svg --transparent stree.drawio --embed -p 10 -o packed-eytzinger.svg
