gif:
    ffmpeg -y -framerate 1 -pattern_type glob -i '*.png' -filter_complex "tpad=stop_mode=clone:stop_duration=2[t];[t]split[s0][s1];[s0]palettegen=max_colors=64[p];[s1][p]paletteuse=dither=bayer" gif.gif
