#+title: About
#+hugo_section: /
#+hugo_aliases: /pages/about
#+hugo_level_offset: 2

Hi there ;)
I completed my PhD in bioinformatics at the [BMI lab](https://bmi.inf.ethz.ch/) at ETH Zurich in early 2025, and am currently a postdoc at KIT in Karlsruhe in the [[https://ae.iti.kit.edu/english/index.php][Algorithm Engineering group]] of [[https://ae.iti.kit.edu/english/sanders.php][Peter Sanders]].
#+begin_export md
My PhD started with work on near-linear algorithms for edit distance
({{% tag pairwise-alignment %}}pairwise alignment{{% /tag %}}), and continued with more theoretical work on
{{% tag minimizers %}}minimizers{{% /tag %}}.
Currently, I mostly focus on algorithm engineering of various (mostly classic)
methods in bioinformatics ({{% tag hpc %}}hpc{{% /tag %}}).
#+end_export

This blog is where I dump my thoughts on my research. It includes
numerous short notes/remarks/ideas for research, and a few longer posts, some of
which have been turned into papers.

Feel free to use this blog as inspiration and build on the ideas you see here, as
long as you cite appropriately.

If you spot mistakes or have suggestions for improvement,
comment at the bottom of each page or make an issue on the [[https://github.com/RagnarGrootKoerkamp/research][GitHub]] source for
this blog.

* Contact
In order of preference:
- Discord, but DM me elsewhere first ;)
- [[https://bsky.app/profile/curiouscoding.nl][Bsky @curiouscoding.nl]]
- ragnar.grootkoerkamp@gmail.com
- [[https://x.com/curious_coding][Twitter @curious_coding]]

* Trivia (i.e. i18n)

My first name is /Ragnar/.  My last name is /Groot Koerkamp/. Yes, that has a
space. No, you cannot get away with /Groot/, and no, you cannot say /Koerkamp/.

Don't even try to say /Ragnar G. Koerkamp/. In fact, my middle name starts with
a /G/, so you'd have to write /R. G. Groot Koerkamp/, or
/Groot Koerkamp, R. G./.
To not complicate things more than they already are, use one of the
following for purposes of publishing and citing:

- R. Groot Koerkamp,
- Ragnar Groot Koerkamp,
- Groot Koerkamp, Ragnar,
- Groot Koerkamp, R.,
- ~Groot Koerkamp, Ragnar~ or ~Ragnar {Groot Koerkamp}~ (but not ~Ragnar Groot Koerkamp~) in BibTeX files.

Note that not all BibTex exports get this right. In particular, arXiv does not
support my name, and downloading BibTex entries (derived) from it may give wrong results.


* CV highlights
More [[file:publications.org][here]].

- IMO 2011: [[http://imo-official.org/participant_r.aspx?id=20580][Honourable mention]]
- IMO 2013: [[http://imo-official.org/participant_r.aspx?id=20580][Bronze medal]]
- ICPC world finals 2016: [[https://icpc.global/community/results-2016][51st place]]
- At some point I solved all ~700 [[https://projecteuler.net][Project Euler]] problems at the time. \\
  https://projecteuler.net/profile/ragnargrootkoerkamp.png
- 19th of 38 in the 2021 Google Hash Code finals.
- [[https://pacechallenge.org/2024/results/#results-of-the-parameterized-track][Second place]] in the parameterized track of the [[https://pacechallenge.org/2024/][2024 PACE challenge]].
- [[https://www.p99conf.io/][P99]] conference speaker in [[https://www.p99conf.io/session/40x-faster-binary-search/][2025]] and [[https://www.p99conf.io/2026/04/01/be-part-of-p99-conf-2026/][2026]].

- 2013-2016: double bachelors Mathematics and Physics @ Utrecht University
- 2016-2017: masters Mathematics and the Foundations of Computer Science @
  University of Oxford
- 2017-2020: Software engineer @ Google Zurich
- 2021-2025: PhD bioinformatics @ ETH Zurich
- 2026-2027: Postdoc high throughput bioinformatics @ Karlsruhe Institute of Technology

I am jury member for various programming contests:
- *BAPC*: 2017-2024, head of jury: 2018-2021
- *NWERC*: 2019-present, head of jury: 2022-2026
