#+title: HPRC v2 stats
#+filetags: @misc note data-analysis
#+OPTIONS: ^:{} num: num:t
#+hugo_front_matter_key_replace: author>authors
#+hugo_paired_shortcodes: %notice %detail
#+toc: headlines 3
#+hugo_level_offset: 1
#+date: <2025-12-26 Fri>

The Movi 2 paper [cite:@movi2] builds a fast index on HPRCv2 [cite:@hprc-v2], a collection of
466 human genomes. This posts
collects some statistics on the number of BWT runs ($r$) of this dataset, and
makes an estimate on the number of unique mutations based on that.

#+caption: Number of BWT runs and average run length for a random 3.2Gbp string, a human genome, and HPRCv1 and v2. The average run-length in HPRC is taken from [cite/t:@movi2].
#+attr_html: :class small
| dataset   | copies | rc? | length (Gbp) | avg run-len | runs (G) | est total mut's | unique mut rate |
| random    |        | no  | 3.2          |        1.33 |     2.40 |                 |                 |
| CHM13v2.0 |      1 | no  | 3.2          |        1.85 |     1.72 |                 |                 |
| HPRCv1    |     94 | yes | 2x 301       |         134 |     2.25 | 33M             | 1/8900          |
| HPRCv2    |    466 | yes | 2x 1500      |         535 |     2.80 | 68M             | 1/22000         |

TODO: Update for the fact that HPRC run-lengths are for the version _with_ rc!
(Include single human genome with rc)
- https://github.com/mohsenzakeri/Movi/issues/29#issuecomment-3694268341

We see that going from 1 to 94 copies increases the number of runs by only
31%, and then going to 466 copies adds an additional 25% of runs.

In the BWT of copies of a random string of length $n$, each point mutation
creates very roughly (within a factor $2$ of) $\log_\sigma n$ additional runs.
Thus, HPRCv1 [cite:@hprc-v1] contains around $(2.25G - 1.72G) / \log_4(3.2G) = 33M$ mutations,
or 360k per copy. So each copy has a unique mutation roughly every $1/8900$ bases.

For HPRCv2, we have 68M mutations, or 150k per copy, or one new unique mutation every
22k bases.

#+print_bibliography:
