#+title: List of interesting blogs
#+filetags: @misc
#+OPTIONS: ^:{}
#+hugo_front_matter_key_replace: author>authors
#+toc: headlines 3
#+date: <2026-05-05 Tue>

These are some links to interesting posts around the web, with some quick quotes/notes.

* April 2026: [[https://davidbessis.substack.com/p/the-fall-of-the-theorem-economy][The fall of the theorem economy]] - David Bessis
  #+begin_quote
  from the moment I conceived of Theorem 0.5, I knew it was true and that proving it would be straightforward.
  #+end_quote
  
  Too long but wow:
  
  #+begin_quote
Official math manifests itself as a formal deduction system where you start from axioms and mechanically derive theorems. This is a nerd’s paradise, a world where truth takes binary values, reasoning is either valid or invalid, and there is technically no room for bullshit.

Secret math is the human part of the story—why official math was invented, how we can successfully interact with it, its effects on our brains, and the bizarre mental techniques through which mathematicians continuously expand its territory.

Secret math never made it to the curriculum, because it lacks the defining qualities of official math, and also because it feels peripheral. Official math is cold, hard, logical, objective, and it is rumored to be the language of the universe. Secret math is soft, fuzzy, subjective and, by contrast, it looks like cheap pedagogical backstory.

No wonder professional mathematicians have such a dissociative view of their job.

The first rule of the Intuition Club is: you don’t talk about the Intuition Club. The second rule is, if you really want to talk about intuition, make it sound casual and accessory, because we ain’t the psychology department. The third rule is definitions are worth zero points, expository work counts negative, and the best jobs should always go to the people who proved the hardest theorems.
  #+end_quote

  Quoting Bill Thurston:
  #+begin_quote
Mathematics only exists in a living community of mathematicians that spreads understanding and breathes life into ideas both old and new. The real satisfaction from mathematics is in learning from others and sharing with others.
  #+end_quote

  #+begin_quote
This is how the system worked for millennia. Mathematicians created value by introducing new concepts, but the rule was that only theorems could put bread on the table.
  #+end_quote

  #+begin_quote
In the human way of doing math, theorem-proving and concept-building walk hand in hand, which forces proofs to be intelligible (if only to their authors).
  #+end_quote

  #+begin_quote
Kontorovich has a great expression for what is missing—canonization:

> By canonization, I mean the process of taking a local, one-off formalization and turning it into library mathematics: general, reusable, coherent, efficient, and compatible with the rest
  #+end_quote

  Sounds like the same problem as AI writing a bunch of messy code instead of
  reusable libraries?

  #+begin_quote
The problem with unintelligible mathematics isn’t that it might be false. It is that it is literally meaningless, in the sense that it doesn’t compile on the only hardware that is currently able to make sense of it and appreciate its value—the human brain.
  #+end_quote

  #+begin_quote
formalized mathematics will now develop in two separate layers, an intelligible
layer embodied by Mathlib, and an unintelligible layer we might call Mathslop, a library of results that are known to be correct via proofs that no human has ever understood.
  #+end_quote

  #+begin_quote
The rise of intuition-maxxers.
  #+end_quote
