#+TITLE: Open Science
#+HUGO_TAGS: science
#+date:  <2021-10-19 Tue>

Let's go over some reasons for why I'm writing this blog.

* The internet is more accessible than papers

The inspiration for this blog is the post on [[https://alexbowe.com/succinct-debruijn-graphs/][Succinct de Bruijn Graphs]] by Alex Bowe.
I think blog posts are a great way to quickly learn about new
ideas and concepts, since they are usually more accessible than papers.
A blog post can omit some of the more formal text required in papers
and spend more time explaining things on an intuitive level. This way,
scientific concepts can be understood by a larger audience than just those
actively working on it.

* Focus on algorithms, instead of results

At least in bioinformatics, my feeling is that papers often focus a lot on
results.  Given my background in theoretical mathematics and computer science,
to me the interesting part is really to understand the ideas/methods/algorithms
used to obtain a result. Once you understand the methods, you can try to build
on them and improve them.

* Faster communication

Another goal of this blog is to increase the speed with which ideas spread
through the community. If I were to have an idea now (I do; watch this space) it
could take me[fn::I don't have much actual experience; numbers are for
illustration only.]:
- a few weeks to write the code;
- a few months to define metrics, run experiments, and compare with competitors;
- a month to write and a submit a paper;
- half a year to get review feedback;
- another half year till publishing.

Taken together, it wouldn't be uncommon for this process to take over a year.
Given that my PhD should only last 3 to 4 years, this only allows for very
few communication round trips.

Instead, I could write a blog post about it today, and it could be read
tomorrow. Of course a blog post does not go through a review process, but just
learning about some new concepts and ideas can spark new creativity and research.

* Open research process

As you guessed, I believe a lot in open science. Having spent some time working
on open source projects, contributing to the world gives me a great feeling, and
I do not see why it should be any other way.

It is a good thing most research today is published in open access journals and
posted on Arxiv, but I think we can take this one step further and also open up
access to the research process itself. My goal is for all my experiments to be
reproducible by myself and others, and allow others to easily improve on them.

* Collaborative science

Really, research is most fun when done with like-minded people. Why do academic
groups need to compete against each other and keep their ideas to themselves,
when working together is more fun and more productive?
See for example the results of the [[https://en.wikipedia.org/wiki/Polymath_Project][Polymath Project]] where mathematicians
collaborated to solve open problems.
I hope this blog will inspire some more collaboration in bioinformatics as well, so
please reach out if you think my work is interesting!

** Authorship

Collaborative projects will have multiple authors. As illustrated by the
Polymath project, where either multiple authors are listed or a pseudonym is
used, this shouldn't be a problem.
