name: Deploy site
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy site
    runs-on: self-hosted
    steps:
      - name: build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd /srv/nginx/curiouscoding.nl/ \
          && git fetch https://${GITHUB_TOKEN}@github.com/ragnargrootkoerkamp/research.git \
          && git reset --hard FETCH_HEAD \
          && git submodule update \
          && make build
